// frontend/src/RequestorDashboard.tsx
import { useState, useEffect, FormEvent } from 'react';
import axios from 'axios';
import { Plus, Download, RefreshCw, Upload } from 'lucide-react';

import { useMsal } from "@azure/msal-react";
import { useLanguage, t } from './i18n';

const API_BASE = 'http://localhost:3001/api';

interface UploadRequest {
  partitionKey: string;
  rowKey: string;
  uploaderEmail: string;
  requestedFileTypes: string;
  status: string;
  expiresAt: string;
  blobUri?: string;
  allowMultiple?: boolean;
  fileStatuses?: string;
  requestNumber: string;
  caseNumber: string;
  downloaderEmail?: string;
  sharedForDownload?: boolean;
  downloadCompletedAt?: string;
}

interface FileShare {
  partitionKey: string;
  rowKey: string;
  originalFilename: string;
  status: string;
  expiresAt: string;
  blobUri?: string;
  downloaderEmail?: string;
  requestNumber: string;
  caseNumber: string;
}

export default function RequestorDashboard() {
  const { instance, accounts } = useMsal();
  const { lang } = useLanguage();
  
  const getAxiosConfig = async () => {
    if (accounts.length > 0) {
      try {
        const response = await instance.acquireTokenSilent({
          scopes: ["User.Read"],
          account: accounts[0]
        });
        return { headers: { Authorization: `Bearer ${response.accessToken}` } };
      } catch (e) {
        return { headers: { 'x-user-email': accounts[0].username } };
      }
    }
    return {};
  };

  const [requests, setRequests] = useState<UploadRequest[]>([]);
  const [shares, setShares] = useState<FileShare[]>([]);
  const [showConfig, setShowConfig] = useState(false);
  const [showShareForm, setShowShareForm] = useState(false);
  const [newRequest, setNewRequest] = useState({ 
    uploaderEmail: '', 
    requestedFileTypes: 'pdf,xlsx',
    expirationDays: '7',
    allowMultiple: false,
    caseNumber: ''
  });
  const [shareFile, setShareFile] = useState<File | null>(null);
  const [uploadingShare, setUploadingShare] = useState(false);
  const [newShare, setNewShare] = useState({ 
    downloaderEmail: '', 
    expirationDays: '7',
    caseNumber: ''
  });
  const [loading, setLoading] = useState(false);
  
  useEffect(() => {
    fetchRequests();
    fetchShares();
  }, [accounts]); 

  const fetchRequests = async () => {
    try {
      const config = await getAxiosConfig();
      const { data } = await axios.get<UploadRequest[]>(`${API_BASE}/requests`, config);
      setRequests(data);
    } catch (error) {
      console.error('Failed to fetch requests', error);
    }
  };

  const fetchShares = async () => {
    try {
      const config = await getAxiosConfig();
      const { data } = await axios.get<FileShare[]>(`${API_BASE}/shares`, config);
      setShares(data);
    } catch (error) {
      console.error('Failed to fetch shares', error);
    }
  };

  const handleCreate = async (e: FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const config = await getAxiosConfig();
      await axios.post(`${API_BASE}/requests`, newRequest, config);
      setShowConfig(false);
      setNewRequest({ uploaderEmail: '', requestedFileTypes: 'pdf,xlsx', expirationDays: '7', allowMultiple: false, caseNumber: '' });
      fetchRequests();
    } catch (error) {
      console.error('Failed to create request', error);
      alert('Error creating request. See console.');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async (token: string, blobName?: string) => {
    try {
      const config = await getAxiosConfig();
      const { data } = await axios.get<{ url: string }>(`${API_BASE}/requests/${token}/download${blobName ? `?filename=${encodeURIComponent(blobName)}` : ''}`, config);
      window.open(data.url, '_blank');
    } catch (error) {
      alert('Failed to get download link or file is not clean.');
    }
  };

  const shareToSharePoint = async (token: string, blobName?: string) => {
    try {
      // Get the file download URL
      const config = await getAxiosConfig();
      const { data } = await axios.get<{ url: string }>(`${API_BASE}/requests/${token}/download${blobName ? `?filename=${encodeURIComponent(blobName)}` : ''}`, config);
      
      // Download the file
      const fileResponse = await axios.get(data.url, { responseType: 'blob' });
      const fileBlob = fileResponse.data;
      
      // Get Microsoft Graph token
      const tokenResponse = await instance.acquireTokenSilent({
        scopes: ["https://graph.microsoft.com/Files.ReadWrite.All", "https://graph.microsoft.com/Sites.ReadWrite.All"],
        account: accounts[0]
      });
      
      // Upload to SharePoint - using default Documents library
      const sharePointUrl = `https://graph.microsoft.com/v1.0/sites/root/drive/root:/${encodeURIComponent(blobName || 'uploaded-file')}`;
      
      await axios.put(sharePointUrl, fileBlob, {
        headers: {
          'Authorization': `Bearer ${tokenResponse.accessToken}`,
          'Content-Type': fileBlob.type || 'application/octet-stream'
        }
      });
      
      alert('File successfully uploaded to SharePoint!');
    } catch (error) {
      console.error('Failed to share to SharePoint', error);
      alert('Failed to upload file to SharePoint. Please check your permissions.');
    }
  };

  const inviteDownloader = async (token: string, blobName?: string) => {
    const downloaderEmail = window.prompt('Downloader email (recipient for secure link):');
    if (!downloaderEmail) return;

    try {
      const config = await getAxiosConfig();
      await axios.post(`${API_BASE}/requests/${token}/invite-downloader`, { 
        downloaderEmail,
        blobName 
      }, config);
      alert('Downloader invitation email sent successfully. The file has been added to your Shared Files list.');
      fetchShares(); // Refresh the shares list to show the new share
    } catch (error) {
      console.error('Failed to send downloader invite', error);
      alert('Failed to send downloader invite.');
    }
  };

  const handleShareFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setShareFile(e.target.files[0]);
    }
  };

  const uploadAndShareFile = async (e: FormEvent) => {
    e.preventDefault();
    if (!shareFile || !newShare.downloaderEmail) return;
    setUploadingShare(true);

    try {
      const config = await getAxiosConfig();
      
      // Step 1: Get upload SAS with expiration
      const sasRes = await axios.post<{ url: string; blobName: string; token: string }>(
        `${API_BASE}/shares/upload`,
        { 
          filename: shareFile.name,
          expirationDays: parseInt(newShare.expirationDays),
          caseNumber: newShare.caseNumber
        },
        config
      );
      const { url, blobName, token } = sasRes.data;

      // Step 2: Upload file to blob
      await axios.put(url, shareFile, {
        headers: {
          'x-ms-blob-type': 'BlockBlob',
          'Content-Type': shareFile.type || 'application/octet-stream'
        }
      });

      // Step 3: Confirm upload
      await axios.post(
        `${API_BASE}/shares/confirm`,
        { token, blobName, filename: shareFile.name },
        config
      );

      // Step 4: Invite downloader
      await axios.post(
        `${API_BASE}/shares/${token}/invite`,
        { downloaderEmail: newShare.downloaderEmail },
        config
      );

      alert('File uploaded and downloader invitation sent successfully!');
      setShareFile(null);
      setNewShare({ downloaderEmail: '', expirationDays: '7', caseNumber: '' });
      setShowShareForm(false);
      fetchShares();
    } catch (error) {
      console.error('Upload error', error);
      alert('Failed to upload file and send invitation.');
    } finally {
      setUploadingShare(false);
    }
  };

  const getStatusBadge = (status: string) => {
    switch(status) {
      case 'Pending': return <span className="badge badge-warning">{status}</span>;
      case 'Uploaded': return <span className="badge badge-info">{status}</span>;
      case 'Scanning': return <span className="badge badge-primary">{status}</span>;
      case 'Clean': return <span className="badge badge-success">{status}</span>;
      case 'Malicious': return <span className="badge badge-danger">{status}</span>;
      case 'Awaiting Download': return <span className="badge badge-secondary">{status}</span>;
      case 'Downloaded': return <span className="badge badge-success">✓ {status}</span>;
      default: return <span className="badge">{status}</span>;
    }
  };

  const getFileStatus = (req: UploadRequest, blobName: string) => {
    if (!req.fileStatuses) return req.status;
    try {
      const statuses = JSON.parse(req.fileStatuses);
      return statuses[blobName] || req.status;
    } catch {
      return req.status;
    }
  };

  return (
    <div>
      <h1 id="main-content">{t('dashboard_title', lang)}</h1>
      
      <p>{t('dashboard_desc', lang)} {t('logged_in_as', lang)} <strong>{accounts[0]?.username || 'admin@example.com'}</strong>.</p>
        
      <button className="btn btn-primary" onClick={() => setShowConfig(!showConfig)} aria-expanded={showConfig}>
        <Plus size={16} aria-hidden="true" style={{verticalAlign: '-3px', marginRight: '5px'}}/>
        {t('create_request', lang)}
      </button>

      {showConfig && (
        <fieldset>
          <legend>{t('req_details', lang)}</legend>
          <form onSubmit={handleCreate}>
            <div className="form-group">
              <label htmlFor="uploaderEmail">{t('uploader_email', lang)} <span className="required">{t('required', lang)}</span></label>
              <span className="hint-text">{t('hint_email', lang)}</span>
              <input 
                type="email" 
                className="form-control"
                id="uploaderEmail"
                required
                value={newRequest.uploaderEmail}
                onChange={e => setNewRequest({...newRequest, uploaderEmail: e.target.value})}
              />
            </div>
            <div className="form-group">
              <label htmlFor="allowedTypes">{t('allowed_types', lang)} <span className="required">{t('required', lang)}</span></label>
              <span className="hint-text">{t('hint_types', lang)}</span>
              <input 
                type="text" 
                className="form-control"
                id="allowedTypes"
                required
                value={newRequest.requestedFileTypes}
                onChange={e => setNewRequest({...newRequest, requestedFileTypes: e.target.value})}
              />
            </div>
            <div className="form-group">
              <label htmlFor="caseNumber">CASE Number</label>
              <span className="hint-text">Optional: Enter custom case number for tracking. If not provided, a unique RQ-* number will be auto-generated.</span>
              <input 
                type="text" 
                className="form-control"
                id="caseNumber"
                value={newRequest.caseNumber}
                onChange={e => setNewRequest({...newRequest, caseNumber: e.target.value})}
                placeholder="e.g., INV-2024-001"
              />
            </div>
            <div className="form-group" style={{ marginBottom: '15px' }}>
              <label htmlFor="allowMultiple" style={{ fontWeight: 'normal' }}>
                <input 
                  type="checkbox" 
                  id="allowMultiple"
                  checked={newRequest.allowMultiple}
                  onChange={e => setNewRequest({...newRequest, allowMultiple: e.target.checked})}
                  style={{ marginRight: '8px' }}
                />
                {t('allow_multiple', lang)}
              </label>
            </div>
            <div className="form-group">
              <label htmlFor="expirationDays">{t('link_exp', lang)} <span className="required">{t('required', lang)}</span></label>
              <select 
                className="form-control" 
                id="expirationDays" 
                value={newRequest.expirationDays}
                onChange={e => setNewRequest({...newRequest, expirationDays: e.target.value})}
              >
                <option value="1">1 {t('day', lang)}</option>
                <option value="7">7 {t('days', lang)}</option>
                <option value="14">14 {t('days', lang)}</option>
                <option value="30">30 {t('days', lang)}</option>
              </select>
            </div>
            <div style={{ marginTop: '1.5em' }}>
              <button className="btn btn-primary" type="submit" disabled={loading}>
                {loading ? '...' : t('submit', lang)}
              </button>
              <button type="button" className="btn btn-default" style={{ marginLeft: '10px' }} onClick={() => setShowConfig(false)}>
                {t('cancel', lang)}
              </button>
            </div>
          </form>
        </fieldset>
      )}

      <button className="btn btn-primary" onClick={() => setShowShareForm(!showShareForm)} aria-expanded={showShareForm} style={{ marginLeft: '10px' }}>
        <Upload size={16} aria-hidden="true" style={{verticalAlign: '-3px', marginRight: '5px'}}/>
        Share a File
      </button>

      {showShareForm && (
        <fieldset style={{ marginTop: '1em' }}>
          <legend>Share File with Downloader</legend>
          <form onSubmit={uploadAndShareFile}>
            <div className="form-group">
              <label htmlFor="shareFile">Select File to Share <span className="required">*</span></label>
              <input 
                type="file" 
                className="form-control"
                id="shareFile"
                onChange={handleShareFile}
                required
              />
              {shareFile && <p style={{ marginTop: '0.5em', fontSize: '0.9em', color: '#666' }}>Selected: {shareFile.name}</p>}
            </div>
            <div className="form-group">
              <label htmlFor="downloaderEmail">Downloader Email <span className="required">*</span></label>
              <span className="hint-text">Email address of the person who will download the file</span>
              <input 
                type="email" 
                className="form-control"
                id="downloaderEmail"
                required
                value={newShare.downloaderEmail}
                onChange={e => setNewShare({...newShare, downloaderEmail: e.target.value})}
              />
            </div>
            <div className="form-group">
              <label htmlFor="shareExpirationDays">Link Expiration <span className="required">*</span></label>
              <select 
                className="form-control" 
                id="shareExpirationDays" 
                value={newShare.expirationDays}
                onChange={e => setNewShare({...newShare, expirationDays: e.target.value})}
              >
                <option value="1">1 Day</option>
                <option value="7">7 Days</option>
                <option value="14">14 Days</option>
                <option value="30">30 Days</option>
              </select>
            </div>
            <div className="form-group">
              <label htmlFor="shareCaseNumber">CASE Number</label>
              <span className="hint-text">Optional: Enter custom case number for tracking. If not provided, a unique RQ-* number will be auto-generated.</span>
              <input 
                type="text" 
                className="form-control"
                id="shareCaseNumber"
                value={newShare.caseNumber}
                onChange={e => setNewShare({...newShare, caseNumber: e.target.value})}
                placeholder="e.g., INV-2024-001"
              />
            </div>
            <div style={{ marginTop: '1.5em' }}>
              <button className="btn btn-primary" type="submit" disabled={!shareFile || !newShare.downloaderEmail || uploadingShare}>
                {uploadingShare ? 'Uploading and Sending...' : 'Upload and Send Invitation'}
              </button>
              <button type="button" className="btn btn-default" style={{ marginLeft: '10px' }} onClick={() => { 
                setShowShareForm(false); 
                setShareFile(null); 
                setNewShare({ downloaderEmail: '', expirationDays: '7', caseNumber: '' });
              }}>
                Cancel
              </button>
            </div>
          </form>
        </fieldset>
      )}

      <h2>{t('active_requests', lang)}</h2>
      <button className="btn btn-default" onClick={fetchRequests}>
        <RefreshCw size={14} aria-hidden="true" style={{verticalAlign: '-2px', marginRight: '5px'}}/> {t('refresh', lang)}
      </button>

      {requests.length === 0 ? (
        <div className="alert alert-info" style={{ marginTop: '1em' }}>
          {t('no_requests', lang)}
        </div>
      ) : (
        <table className="table">
          <thead>
            <tr>
              <th scope="col">{t('table_request_number', lang)}</th>
              <th scope="col">{t('table_case_number', lang)}</th>
              <th scope="col">{t('table_uploader', lang)}</th>
              <th scope="col">{t('table_type', lang)}</th>
              <th scope="col">{t('table_status', lang)}</th>
              <th scope="col">{t('table_expires', lang)}</th>
              <th scope="col">{t('table_action', lang)}</th>
            </tr>
          </thead>
          <tbody>
            {requests.map(req => (
              <tr key={req.rowKey}>
                <td><strong>{req.requestNumber}</strong></td>
                <td><strong>{req.caseNumber || '--'}</strong></td>
                <td>{req.uploaderEmail}</td>
                <td>{req.requestedFileTypes.toUpperCase()}</td>
                <td>{getStatusBadge(req.status)}</td>
                <td>{new Date(req.expiresAt).toLocaleDateString()}</td>
                <td>
                  {req.blobUri ? (
                    <div>
                      {req.blobUri.split(',').map((blobName: string, idx: number) => {
                        const fileStatus = getFileStatus(req, blobName);
                        return (
                          <div key={idx} style={{ marginBottom: '5px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <button className="btn btn-success" onClick={() => handleDownload(req.rowKey, blobName)}>
                              <Download size={14} aria-hidden="true" style={{verticalAlign: '-2px'}}/> {t('download', lang)} {blobName}
                            </button>
                            {getStatusBadge(fileStatus)}
                            {fileStatus === 'Clean' && (
                              <>
                                <button className="btn btn-secondary btn-small" onClick={() => inviteDownloader(req.rowKey, blobName)}>
                                  Share
                                </button>
                                <button className="btn btn-info btn-small" onClick={() => shareToSharePoint(req.rowKey, blobName)}>
                                  Share to SharePoint
                                </button>
                              </>
                            )}
                          </div>
                        );
                      })}
                    </div>
                  ) : (
                    <span>---</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <h2 style={{ marginTop: '3em' }}>Shared Files</h2>
      <button className="btn btn-default" onClick={fetchShares}>
        <RefreshCw size={14} aria-hidden="true" style={{verticalAlign: '-2px', marginRight: '5px'}}/> {t('refresh', lang)}
      </button>

      {shares.length === 0 ? (
        <div className="alert alert-info" style={{ marginTop: '1em' }}>
          {t('no_shares', lang)}
        </div>
      ) : (
        <table className="table" style={{ marginTop: '1em' }}>
          <thead>
            <tr>
              <th scope="col">{t('table_request_number', lang)}</th>
              <th scope="col">{t('table_case_number', lang)}</th>
              <th scope="col">{t('table_filename', lang)}</th>
              <th scope="col">{t('table_status', lang)}</th>
              <th scope="col">{t('table_downloader', lang)}</th>
              <th scope="col">{t('table_expires', lang)}</th>
              <th scope="col">{t('table_action', lang)}</th>
            </tr>
          </thead>
          <tbody>
            {shares.map(share => (
              <tr key={share.rowKey}>
                <td><strong>{share.requestNumber}</strong></td>
                <td><strong>{share.caseNumber || '--'}</strong></td>
                <td>{share.originalFilename}</td>
                <td>{getStatusBadge(share.status)}</td>
                <td>{share.downloaderEmail || '--'}</td>
                <td>{new Date(share.expiresAt).toLocaleDateString()}</td>
                <td>
                  {!share.downloaderEmail && share.blobUri ? (
                    <button className="btn btn-small btn-info" onClick={() => {
                      const email = window.prompt('Downloader email:');
                      if (email) {
                        axios.post(`${API_BASE}/shares/${share.rowKey}/invite`, { downloaderEmail: email }, { headers: { Authorization: `Bearer token` } })
                          .then(() => { alert('Invitation sent!'); fetchShares(); })
                          .catch(() => alert('Failed to send invitation'));
                      }
                    }}>
                      Invite Downloader
                    </button>
                  ) : share.downloaderEmail ? (
                    <span style={{ color: '#666' }}>Invited</span>
                  ) : (
                    <span style={{ color: '#999' }}>Pending upload</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

// frontend/src/RequestorDashboard.vue
<template>
  <div>
    <h1 id="main-content">{{ t('dashboard_title') }}</h1>
    
    <p>{{ t('dashboard_desc') }} {{ t('logged_in_as') }} <strong>{{ activeAccount?.username || 'admin@example.com' }}</strong>.</p>
      
    <button class="btn btn-primary" @click="showConfig = !showConfig" :aria-expanded="showConfig">
      <Plus :size="16" aria-hidden="true" style="vertical-align: -3px; margin-right: 5px;" />
      {{ t('create_request') }}
    </button>

    <fieldset v-if="showConfig">
      <legend>{{ t('req_details') }}</legend>
      <form @submit.prevent="handleCreate">
        <!-- omitted some fields for brevity, they should mirror React version -->
        <div class="form-group">
          <label for="uploaderEmail">{{ t('uploader_email') }} <span class="required">{{ t('required') }}</span></label>
          <span class="hint-text">{{ t('hint_email') }}</span>
          <input type="email" class="form-control" id="uploaderEmail" required v-model="newRequest.uploaderEmail" />
        </div>
        <div class="form-group">
           <label for="allowedTypes">{{ t('allowed_types') }} <span class="required">{{ t('required') }}</span></label>
           <span class="hint-text">{{ t('hint_types') }}</span>
           <input type="text" class="form-control" id="allowedTypes" required v-model="newRequest.requestedFileTypes" />
        </div>
        <div class="form-group">
          <label for="caseNumber">{{ t('case_number') }}</label>
          <span class="hint-text">{{ t('case_number_hint') }}</span>
          <input type="text" class="form-control" id="caseNumber" v-model="newRequest.caseNumber" :placeholder="t('case_number_placeholder')" />
        </div>
        <div class="form-group" style="display: flex; gap: 15px;">
          <div style="flex: 1;">
            <label for="identifierName">{{ t('identifier_name') || 'Identifier Name' }}</label>
            <input type="text" class="form-control" id="identifierName" v-model="newRequest.identifierName" />
          </div>
          <div style="flex: 1;">
            <label for="identifierValue">{{ t('identifier_value') || 'Identifier Value' }}</label>
            <input type="text" class="form-control" id="identifierValue" v-model="newRequest.identifierValue" />
          </div>
        </div>
        <div class="form-group">
          <label for="jsonMetadata">{{ t('json_metadata') || 'JSON Metadata' }}</label>
          <textarea class="form-control" id="jsonMetadata" v-model="newRequest.jsonMetadata" rows="3" placeholder='{"key": "value"}'></textarea>
        </div>
        <div class="form-group" style="margin-bottom: 15px;">
          <label for="allowMultiple" style="font-weight: normal;">
            <input type="checkbox" id="allowMultiple" v-model="newRequest.allowMultiple" style="margin-right: 8px;" />
            {{ t('allow_multiple') }}
          </label>
        </div>
        <div class="form-group">
           <label for="expirationDays">{{ t('link_exp') }} <span class="required">{{ t('required') }}</span></label>
           <select class="form-control" id="expirationDays" v-model="newRequest.expirationDays">
             <option value="1">1 {{ t('day') }}</option>
             <option value="7">7 {{ t('days') }}</option>
             <option value="14">14 {{ t('days') }}</option>
             <option value="30">30 {{ t('days') }}</option>
           </select>
        </div>
        <div style="margin-top: 1.5em;">
          <button class="btn btn-primary" type="submit" :disabled="loading">
            {{ loading ? '...' : t('submit') }}
          </button>
          <button type="button" class="btn btn-default" style="margin-left: 10px;" @click="showConfig = false">
            {{ t('cancel') }}
          </button>
        </div>
      </form>
    </fieldset>

    <h2>{{ t('active_requests') }}</h2>
    <button class="btn btn-default" @click="fetchRequests">
      <RefreshCw :size="14" aria-hidden="true" style="vertical-align: -2px; margin-right: 5px;" /> {{ t('refresh') }}
    </button>

    <div v-if="requests.length === 0" class="alert alert-info" style="margin-top: 1em;">
      {{ t('no_requests') }}
    </div>
    <table v-else class="table">
      <thead>
        <tr>
          <!-- basic rendering -->
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleRequestSort('requestNumber')">{{ t('table_request_number') }}{{ getSortIndicator(requestSort, 'requestNumber') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleRequestSort('caseNumber')">{{ t('table_case_number') }}{{ getSortIndicator(requestSort, 'caseNumber') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleRequestSort('identifierName')">{{ t('identifier_name') || 'Identifier Name' }}{{ getSortIndicator(requestSort, 'identifierName') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleRequestSort('identifierValue')">{{ t('identifier_value') || 'Identifier Value' }}{{ getSortIndicator(requestSort, 'identifierValue') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleRequestSort('uploaderEmail')">{{ t('table_uploader') }}{{ getSortIndicator(requestSort, 'uploaderEmail') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleRequestSort('requestedFileTypes')">{{ t('table_type') }}{{ getSortIndicator(requestSort, 'requestedFileTypes') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleRequestSort('status')">{{ t('table_status') }}{{ getSortIndicator(requestSort, 'status') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleRequestSort('expiresAt')">{{ t('table_expires') }}{{ getSortIndicator(requestSort, 'expiresAt') }}</th>
          <th scope="col">{{ t('table_action') }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="req in sortedRequests" :key="req.rowKey">
          <td><strong>{{ req.requestNumber }}</strong></td>
          <td><strong>{{ req.caseNumber || '--' }}</strong></td>
          <td>{{ req.identifierName || '--' }}</td>
          <td>{{ req.identifierValue || '--' }}</td>
          <td>{{ req.uploaderEmail }}</td>
          <td>{{ req.requestedFileTypes.toUpperCase() }}</td>
          <td>
             <span class="badge" :class="getBadgeClass(req.status)">{{ req.status === 'Downloaded' ? '✓ ' : '' }}{{ translateStatus(req.status) }}</span>
          </td>
          <td>{{ new Date(req.expiresAt).toLocaleDateString() }}</td>
          <td>
             <div v-if="req.blobUri">
               <div v-for="(blobName, idx) in req.blobUri.split(',')" :key="idx" style="margin-bottom: 5px; display: flex; align-items: center; gap: 8px;">
                 <button v-if="getFileStatus(req, blobName) === 'Malicious'" class="btn btn-danger" disabled>
                   <Download :size="14" aria-hidden="true" style="vertical-align: -2px;" /> {{ t('download') }} {{ blobName }}
                 </button>
                 <button v-else-if="getFileStatus(req, blobName) !== 'Clean'" class="btn btn-secondary" disabled>
                   <Download :size="14" aria-hidden="true" style="vertical-align: -2px;" /> {{ t('download') }} {{ blobName }}
                 </button>
                 <button v-else class="btn btn-success" @click="handleDownload(req.rowKey, blobName)">
                   <Download :size="14" aria-hidden="true" style="vertical-align: -2px;" /> {{ t('download') }} {{ blobName }}
                 </button>
                 
                 <span class="badge" :class="getBadgeClass(getFileStatus(req, blobName))">
                   {{ getFileStatus(req, blobName) === 'Downloaded' ? '✓ ' : '' }}{{ translateStatus(getFileStatus(req, blobName)) }}
                 </span>

                 <template v-if="getFileStatus(req, blobName) === 'Clean'">
                   <button class="btn btn-secondary btn-small" @click="inviteDownloader(req.rowKey, blobName)">
                     {{ t('share') }}
                   </button>
                   <button class="btn btn-info btn-small" @click="shareToSharePoint(req.rowKey, blobName)">
                     {{ t('share_to_sharepoint') }}
                   </button>
                 </template>
               </div>
             </div>
             <span v-else>---</span>
          </td>
        </tr>
      </tbody>
    </table>
    <!-- Share File Section -->
    <button class="btn btn-primary" @click="showShareForm = !showShareForm" :aria-expanded="showShareForm" style="margin-left: 10px;">
      <Upload :size="16" aria-hidden="true" style="vertical-align: -3px; margin-right: 5px;"/>
      {{ t('share_a_file') }}
    </button>

    <fieldset v-if="showShareForm" style="margin-top: 1em;">
      <legend>{{ t('share_file_with_downloader') }}</legend>
      <form @submit.prevent="uploadAndShareFile">
        <div class="form-group">
          <label for="shareFile">{{ t('select_file_to_share') }} <span class="required">*</span></label>
          <input type="file" class="form-control" id="shareFile" @change="handleShareFile" required />
          <p v-if="shareFile" style="margin-top: 0.5em; font-size: 0.9em; color: #666;">{{ t('selected') }}: {{ shareFile.name }}</p>
        </div>
        <div class="form-group">
          <label for="downloaderEmail">{{ t('downloader_email') }} <span class="required">*</span></label>
          <span class="hint-text">{{ t('downloader_email_hint') }}</span>
          <input type="email" class="form-control" id="downloaderEmail" required v-model="newShare.downloaderEmail" />
        </div>
        <div class="form-group">
          <label for="shareExpirationDays">{{ t('link_expiration') }} <span class="required">*</span></label>
          <select class="form-control" id="shareExpirationDays" v-model="newShare.expirationDays">
            <option value="1">{{ t('one_day') }}</option>
            <option value="7">{{ t('seven_days') }}</option>
            <option value="14">{{ t('fourteen_days') }}</option>
            <option value="30">{{ t('thirty_days') }}</option>
          </select>
        </div>
        <div style="margin-top: 1.5em;">
          <button class="btn btn-primary" type="submit" :disabled="!shareFile || !newShare.downloaderEmail || uploadingShare">
            {{ uploadingShare ? t('uploading_and_sending') : t('upload_and_send_invitation') }}
          </button>
          <button type="button" class="btn btn-default" style="margin-left: 10px;" @click="showShareForm = false; shareFile = null">
            {{ t('cancel') }}
          </button>
        </div>
      </form>
    </fieldset>

    <h2 style="margin-top: 3em;">{{ t('shared_files') }}</h2>
    <button class="btn btn-default" @click="fetchShares">
      <RefreshCw :size="14" aria-hidden="true" style="vertical-align: -2px; margin-right: 5px;" /> {{ t('refresh') }}
    </button>

    <div v-if="shares.length === 0" class="alert alert-info" style="margin-top: 1em;">
      {{ t('no_shares') }}
    </div>
    <table v-else class="table" style="margin-top: 1em;">
      <thead>
        <tr>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleShareSort('requestNumber')">{{ t('table_request_number') }}{{ getSortIndicator(shareSort, 'requestNumber') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleShareSort('caseNumber')">{{ t('table_case_number') }}{{ getSortIndicator(shareSort, 'caseNumber') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleShareSort('identifierName')">{{ t('identifier_name') || 'Identifier Name' }}{{ getSortIndicator(shareSort, 'identifierName') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleShareSort('identifierValue')">{{ t('identifier_value') || 'Identifier Value' }}{{ getSortIndicator(shareSort, 'identifierValue') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleShareSort('originalFilename')">{{ t('table_filename') }}{{ getSortIndicator(shareSort, 'originalFilename') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleShareSort('status')">{{ t('table_status') }}{{ getSortIndicator(shareSort, 'status') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleShareSort('downloaderEmail')">{{ t('table_downloader') }}{{ getSortIndicator(shareSort, 'downloaderEmail') }}</th>
          <th scope="col" style="cursor: pointer; user-select: none;" @click="handleShareSort('expiresAt')">{{ t('table_expires') }}{{ getSortIndicator(shareSort, 'expiresAt') }}</th>
          <th scope="col">{{ t('table_action') }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="share in sortedShares" :key="share.rowKey">
          <td><strong>{{ share.requestNumber }}</strong></td>
          <td><strong>{{ share.caseNumber || '--' }}</strong></td>
          <td>{{ share.identifierName || '--' }}</td>
          <td>{{ share.identifierValue || '--' }}</td>
          <td>{{ share.originalFilename }}</td>
          <td><span class="badge" :class="getBadgeClass(share.status)">{{ share.status === 'Downloaded' ? '✓ ' : '' }}{{ translateStatus(share.status) }}</span></td>
          <td>{{ share.downloaderEmail || '--' }}</td>
          <td>{{ new Date(share.expiresAt).toLocaleDateString() }}</td>
          <td>
            <button v-if="!share.downloaderEmail && share.blobUri" class="btn btn-small btn-info" @click="inviteDownloader(share.rowKey)">
              {{ t('invite_downloader') }}
            </button>
            <span v-else-if="share.downloaderEmail" style="color: #666;">{{ t('invited') }}</span>
            <span v-else style="color: #999;">{{ t('pending_upload') }}</span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, inject, computed } from 'vue';
import axios from 'axios';
import { Plus, Download, RefreshCw, Upload } from 'lucide-vue-next';
import { useLanguage, t as tRoot } from './i18n';
import { PublicClientApplication } from '@azure/msal-browser';

const API_BASE = 'http://localhost:3001/api';
const msal = inject<PublicClientApplication>('msal')!;
const { lang } = useLanguage();

const t = (key: string) => tRoot(key);
const activeAccount = ref(msal.getAllAccounts()[0] || null);

const requests = ref<any[]>([]);
const shares = ref<any[]>([]);
const showConfig = ref(false);
const showShareForm = ref(false);
const newRequest = ref({ 
  uploaderEmail: '', 
  requestedFileTypes: 'pdf,xlsx',
  expirationDays: '7',
  allowMultiple: false,
  caseNumber: '',
  identifierName: '',
  identifierValue: '',
  jsonMetadata: ''
});
const loading = ref(false);

type SortDirection = 'asc' | 'desc';
interface SortConfig<T> { key: keyof T | ''; direction: SortDirection }

const requestSort = ref<SortConfig<any>>({ key: '', direction: 'asc' });
const shareSort = ref<SortConfig<any>>({ key: '', direction: 'asc' });

const handleRequestSort = (key: string) => {
  if (requestSort.value.key === key) requestSort.value.direction = requestSort.value.direction === 'asc' ? 'desc' : 'asc';
  else requestSort.value = { key, direction: 'asc' };
};

const handleShareSort = (key: string) => {
  if (shareSort.value.key === key) shareSort.value.direction = shareSort.value.direction === 'asc' ? 'desc' : 'asc';
  else shareSort.value = { key, direction: 'asc' };
};

const getSortIndicator = (config: SortConfig<any>, key: string) => {
  if (config.key === key) return config.direction === 'asc' ? ' ↑' : ' ↓';
  return '';
};

const sortedRequests = computed(() => {
  let sortableItems = [...requests.value];
  if (requestSort.value.key !== '') {
    sortableItems.sort((a, b) => {
      const aVal = a[requestSort.value.key as string] || '';
      const bVal = b[requestSort.value.key as string] || '';
      if (aVal < bVal) return requestSort.value.direction === 'asc' ? -1 : 1;
      if (aVal > bVal) return requestSort.value.direction === 'asc' ? 1 : -1;
      return 0;
    });
  }
  return sortableItems;
});

const sortedShares = computed(() => {
  let sortableItems = [...shares.value];
  if (shareSort.value.key !== '') {
    sortableItems.sort((a, b) => {
      const aVal = a[shareSort.value.key as string] || '';
      const bVal = b[shareSort.value.key as string] || '';
      if (aVal < bVal) return shareSort.value.direction === 'asc' ? -1 : 1;
      if (aVal > bVal) return shareSort.value.direction === 'asc' ? 1 : -1;
      return 0;
    });
  }
  return sortableItems;
});

const getAxiosConfig = async () => {
  if (activeAccount.value) {
    try {
      const response = await msal.acquireTokenSilent({
        scopes: ["User.Read"],
        account: activeAccount.value
      });
      return { headers: { Authorization: `Bearer ${response.accessToken}` } };
    } catch (e) {
      return { headers: { 'x-user-email': activeAccount.value.username } };
    }
  }
  return {};
};

const fetchRequests = async () => {
  try {
    const config = await getAxiosConfig();
    const { data } = await axios.get(`${API_BASE}/requests`, config);
    requests.value = data;
  } catch (error) {
    console.error('Failed to fetch requests', error);
  }
};

const shareFile = ref<File | null>(null);
const uploadingShare = ref(false);
const newShare = ref({ 
  downloaderEmail: '', 
  expirationDays: '7',
  caseNumber: '',
  identifierName: '',
  identifierValue: '',
  jsonMetadata: ''
});

const translateStatus = (status: string) => {
  switch(status) {
    case 'Pending': return t('status_pending');
    case 'Uploaded': return t('status_uploaded');
    case 'Scanning': return t('status_scanning');
    case 'Clean': return t('status_clean');
    case 'Malicious': return t('status_malicious');
    case 'Awaiting Download': return t('status_awaiting_download');
    case 'Downloaded': return t('status_downloaded');
    case 'Ready': return t('status_ready');
    default: return status;
  }
};

const getBadgeClass = (status: string) => {
  switch(status) {
    case 'Pending': return 'badge-warning';
    case 'Uploaded': return 'badge-info';
    case 'Scanning': return 'badge-primary';
    case 'Clean': return 'badge-success';
    case 'Ready': return 'badge-success';
    case 'Malicious': return 'badge-danger';
    case 'Awaiting Download': return 'badge-secondary';
    case 'Downloaded': return 'badge-success';
    default: return 'badge-info';
  }
};

const getFileStatus = (req: any, blobName: string) => {
  if (!req.fileStatuses) return req.status;
  try { return JSON.parse(req.fileStatuses)[blobName] || req.status; } catch { return req.status; }
};

const fetchShares = async () => {
  try {
    const config = await getAxiosConfig();
    const { data } = await axios.get(`${API_BASE}/shares`, config);
    shares.value = data;
  } catch (error) {
    console.error('Failed to fetch shares', error);
  }
};

const inviteDownloader = async (token: string, blobName?: string) => {
  const downloaderEmail = window.prompt(t('downloader_email_prompt'));
  if (!downloaderEmail) return;

  const expirationInput = window.prompt(t('share_expiration_days_prompt'), '7');
  if (!expirationInput) return;

  const expirationDays = parseInt(expirationInput, 10);
  if (isNaN(expirationDays) || expirationDays < 1) {
    alert(t('invalid_expiration_days'));
    return;
  }

  try {
    const config = await getAxiosConfig();
    await axios.post(`${API_BASE}/requests/${token}/invite-downloader`, { 
      downloaderEmail,
      blobName,
      expirationDays
    }, config);
    alert(t('invitation_sent'));
    fetchShares();
  } catch (error) {
    console.error('Failed to send downloader invite', error);
    alert(t('failed_send_invite'));
  }
};

const shareToSharePoint = async (token: string, blobName?: string) => {
  try {
    const config = await getAxiosConfig();
    const { data } = await axios.get(`${API_BASE}/requests/${token}/download${blobName ? `?filename=${encodeURIComponent(blobName)}` : ''}`, config);
    const fileResponse = await axios.get(data.url, { responseType: 'blob' });
    const fileBlob = fileResponse.data;
    
    const tokenResponse = await msal.acquireTokenSilent({
      scopes: ["https://graph.microsoft.com/Files.ReadWrite.All", "https://graph.microsoft.com/Sites.ReadWrite.All"],
      account: activeAccount.value!
    });
    
    const sharePointUrl = `https://graph.microsoft.com/v1.0/sites/root/drive/root:/${encodeURIComponent(blobName || 'uploaded-file')}`;
    
    await axios.put(sharePointUrl, fileBlob, {
      headers: {
        'Authorization': `Bearer ${tokenResponse.accessToken}`,
        'Content-Type': fileBlob.type || 'application/octet-stream'
      }
    });
    
    alert(t('file_uploaded_sharepoint'));
  } catch (error) {
    console.error('Failed to share to SharePoint', error);
    alert(t('failed_upload_sharepoint'));
  }
};

const handleShareFile = (e: Event) => {
  const target = e.target as HTMLInputElement;
  if (target.files && target.files[0]) {
    shareFile.value = target.files[0];
  }
};

const uploadAndShareFile = async () => {
  if (!shareFile.value || !newShare.value.downloaderEmail) return;
  uploadingShare.value = true;
  try {
    const config = await getAxiosConfig();
    const sasRes = await axios.post(
      `${API_BASE}/shares/upload`,
      { 
        filename: shareFile.value.name,
        expirationDays: parseInt(newShare.value.expirationDays),
        caseNumber: newShare.value.caseNumber,
        identifierName: newShare.value.identifierName,
        identifierValue: newShare.value.identifierValue,
        jsonMetadata: newShare.value.jsonMetadata
      },
      config
    );
    const { url, blobName, token } = sasRes.data;

    await axios.put(url, shareFile.value, {
      headers: {
        'x-ms-blob-type': 'BlockBlob',
        'Content-Type': shareFile.value.type || 'application/octet-stream'
      }
    });

    await axios.post(`${API_BASE}/shares/confirm`, { token, blobName, filename: shareFile.value.name }, config);
    await axios.post(`${API_BASE}/shares/${token}/invite`, { downloaderEmail: newShare.value.downloaderEmail }, config);

    alert(t('file_uploaded_invitation_sent'));
    shareFile.value = null;
    newShare.value = { downloaderEmail: '', expirationDays: '7', caseNumber: '', identifierName: '', identifierValue: '', jsonMetadata: '' };
    showShareForm.value = false;
    fetchShares();
  } catch (error) {
    console.error('Upload error', error);
    alert(t('failed_upload_invitation'));
  } finally {
    uploadingShare.value = false;
  }
};

const handleCreate = async () => {
  loading.value = true;
  try {
    const config = await getAxiosConfig();
    await axios.post(`${API_BASE}/requests`, newRequest.value, config);
    showConfig.value = false;
    fetchRequests();
  } catch (error) {
    console.error('Failed to create request', error);
    alert(t('error_creating_request'));
  } finally {
    loading.value = false;
  }
};

const handleDownload = async (token: string, blobName?: string) => {
  try {
    const config = await getAxiosConfig();
    const { data } = await axios.get(`${API_BASE}/requests/${token}/download${blobName ? `?filename=${encodeURIComponent(blobName)}` : ''}`, config);
    window.open(data.url, '_blank');
  } catch (error: any) {
    alert('Failed to get download link.');
  }
};

onMounted(() => {
  fetchRequests();
  fetchShares();
});
</script>
