// frontend/src/UploaderView.tsx
import React, { useState, useEffect, useRef, FormEvent } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import { UploadCloud } from 'lucide-react';
import { useLanguage, t } from './i18n';

const API_BASE = 'http://localhost:3001/api/public';

interface RequestInfo {
  uploaderEmail: string;
  requestedFileTypes: string;
  status: string;
  requiresSecret: boolean;
  blobUri?: string | null;
  allowMultiple?: boolean;
  isClosed?: boolean;
  caseNumber?: string;
  downloadCompletedAt?: string;
}

export default function UploaderView() {
  const { lang } = useLanguage();
  const { token } = useParams<{ token: string }>();
  const [requestInfo, setRequestInfo] = useState<RequestInfo | null>(null);
  const [file, setFile] = useState<File | null>(null);
  
  const [status, setStatus] = useState('loading'); // loading, ready (auth needed), authenticated, uploading, success, error, already_uploaded
  const [secret, setSecret] = useState('');
  const [secretError, setSecretError] = useState('');
  const [fileError, setFileError] = useState('');
  const [cooldown, setCooldown] = useState(0);
  
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (cooldown > 0) {
      const timer = setTimeout(() => setCooldown(cooldown - 1), 1000);
      return () => clearTimeout(timer);
    }
  }, [cooldown]);

  useEffect(() => {
    axios.get<RequestInfo>(`${API_BASE}/requests/${token}`)
      .then(res => {
        // ALWAYS allow them to see the form even if already uploaded, per requirements
        setRequestInfo(res.data);
        if (res.data.isClosed || (res.data.blobUri && !res.data.allowMultiple)) {
          setStatus('already_uploaded');
        } else {
          setStatus(res.data.requiresSecret ? 'ready' : 'authenticated');
        }
      })
      .catch(() => {
          setStatus('error');
      });
  }, [token]);

  const handleAuthenticate = async (e: FormEvent) => {
    e.preventDefault();
    setSecretError('');
    try {
      await axios.post(`${API_BASE}/requests/${token}/validate-secret`, { secret });
      // If it's already closed or completed, validating should show already_uploaded
      if (requestInfo?.isClosed || (requestInfo?.blobUri && !requestInfo?.allowMultiple)) {
        setStatus('already_uploaded');
      } else {
        setStatus('authenticated');
      }
    } catch (err) {
      setSecretError(t('invalid_link_desc', lang));
    }
  };

  const handleSend2fa = async () => {
    try {
      await axios.post(`${API_BASE}/requests/${token}/send-uploader-2fa`);
      setCooldown(60);
      setSecretError('');
      alert('2FA Passcode sent to your email.');
    } catch (err: any) {
      if (err.response?.status === 429) {
        setSecretError('Please wait 1 minute before requesting another code.');
      } else {
        setSecretError('Failed to send 2FA code.');
      }
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const selectedFile = e.target.files[0];
      const allowedExtensions = requestInfo?.requestedFileTypes
        .split(',')
        .map(ext => ext.trim().toLowerCase().replace(/^[\.]/, ''))
        .filter(Boolean) || [];
      const fileExt = selectedFile.name.split('.').pop()?.toLowerCase() || '';

      if (allowedExtensions.length > 0 && fileExt && !allowedExtensions.includes(fileExt)) {
        setFile(null);
        setFileError(`Invalid file type. Allowed: ${requestInfo?.requestedFileTypes}`);
        return;
      }

      setFile(selectedFile);
      setFileError('');
    }
  };

  const handleUpload = async () => {
    if (!file) return;
    setStatus('uploading');

    try {
      const sasRes = await axios.post<{ url: string, blobName: string }>(`${API_BASE}/requests/${token}/sas`, { filename: file.name, secret });
      const { url, blobName } = sasRes.data;

      await axios.put(url, file, {
        headers: {
          'x-ms-blob-type': 'BlockBlob',
          'Content-Type': file.type || 'application/octet-stream'
        }
      });

      await axios.post(`${API_BASE}/requests/${token}/confirm`, { blobName });

      // Refresh data to show currently uploaded files and allow more uploads
      const res = await axios.get<RequestInfo>(`${API_BASE}/requests/${token}`);
      setRequestInfo(res.data);
      setFile(null);
      
      // If allowMultiple is not enabled, mark as closed immediately after 1 upload.
      if (!res.data.allowMultiple) {
          setStatus('success'); // or already_uploaded
      } else {
          setStatus('authenticated');
      }
    } catch (error) {
      console.error('Upload error', error);
      setStatus('error');
    }
  };

  const handleDone = async () => {
    try {
      if (!window.confirm(t('confirm_complete_upload', lang))) {
        return;
      }
      await axios.post(`${API_BASE}/requests/${token}/complete`);
      setStatus('already_uploaded');
    } catch (error) {
      console.error('Complete error', error);
      setStatus('error');
    }
  };

  if (status === 'loading') return <h1 id="main-content">{t('loading', lang)}</h1>;
  if (status === 'already_uploaded') return <div className="alert alert-success"><h2 style={{marginTop:0}}>{t('fulfilled', lang)}</h2><p>{t('fulfilled_desc', lang)}</p></div>;
  if (status === 'error') return <div className="alert alert-danger"><h2 style={{marginTop:0}}>{t('invalid_link', lang)}</h2><p>{t('invalid_link_desc', lang)}</p></div>;
  if (status === 'success') return <div className="alert alert-success"><h2 style={{marginTop:0}}>{t('success', lang)}</h2><p>{t('success_desc', lang)}</p></div>;

  return (
    <div>
      <h1 id="main-content">{t('portal_title', lang)}</h1>
      <p>{t('portal_desc', lang)}</p>
      {requestInfo?.caseNumber && (
        <div style={{ marginBottom: '1em', padding: '1em', backgroundColor: '#f0f0f0', borderLeft: '4px solid #0066cc' }}>
          <strong>{t('case_number_label', lang)}</strong> {requestInfo.caseNumber}
        </div>
      )}

      {status === 'ready' && (
        <fieldset>
          <legend>{t('auth_req', lang)}</legend>
          <p>{t('auth_req_desc', lang)}</p>
          {secretError && <div className="alert alert-danger" role="alert">{secretError}</div>}
          <form onSubmit={handleAuthenticate}>
            <div className="form-group">
              <label htmlFor="secretInput">{t('secret', lang)}</label>
              <input 
                type="password" 
                id="secretInput"
                className="form-control"
                value={secret}
                onChange={e => setSecret(e.target.value)}
                required
              />
            </div>
            <div style={{ display: 'flex', gap: '10px' }}>
              <button type="submit" className="btn btn-primary">{t('access_portal', lang)}</button>
              <button type="button" className="btn btn-default" onClick={handleSend2fa} disabled={cooldown > 0}>
                {cooldown > 0 ? `Wait ${cooldown}s` : 'Send Passcode'}
              </button>
            </div>
          </form>
        </fieldset>
      )}

      {(status === 'authenticated' || status === 'uploading') && requestInfo && (
        <fieldset>
          <legend>{t('upload_doc', lang)}</legend>

          {requestInfo.blobUri && !requestInfo.allowMultiple && (
            <div className="alert alert-success" style={{ marginBottom: '1.5em' }}>
              <strong>{t('upload_complete_single_file', lang)}</strong>
            </div>
          )}
          
          {requestInfo.blobUri && requestInfo.allowMultiple && (
            <div className="alert alert-info" style={{ marginBottom: '1.5em' }}>
              <strong>{t('files_uploaded_for_request', lang)}</strong>
              <ul style={{ margin: '0.5em 0 0', paddingLeft: '1.5em' }}>
                {requestInfo.blobUri.split(',').map((blob: string, idx: number) => (
                  <li key={idx}>{blob}</li>
                ))}
              </ul>
              <p style={{ marginTop: '0.5em' }}>{t('upload_more_files_allowed', lang)}</p>
            </div>
          )}

          {(!requestInfo.blobUri || requestInfo.allowMultiple) && (
            <>
              <p><strong>{t('allowed_file_types', lang)}</strong> {requestInfo.requestedFileTypes}</p>
          
          <div 
            className="dropzone"
            onClick={() => fileInputRef.current?.click()}
            onDragOver={(e) => e.preventDefault()}
            onDrop={(e) => { e.preventDefault(); if(e.dataTransfer.files[0]) setFile(e.dataTransfer.files[0]); }}
            role="button"
            tabIndex={0}
            aria-label={t('click_drag', lang)}
            onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') fileInputRef.current?.click(); }}
          >
            <UploadCloud size={48} className="dropzone-icon" aria-hidden="true" />
            {file ? (
              <p className="dropzone-text">{t('selected', lang)} {file.name} ({(file.size / 1024 / 1024).toFixed(2)} MB)</p>
            ) : (
              <p className="dropzone-text">{t('click_drag', lang)}</p>
            )}
            <input 
              type="file" 
              ref={fileInputRef} 
              style={{ display: 'none' }} 
              onChange={handleFileChange}
              accept={requestInfo.requestedFileTypes.split(',').map(ext => `.${ext.trim()}`).join(',')} 
              aria-hidden="true"
              tabIndex={-1}
            />
          </div>
          {fileError && (
            <div className="alert alert-danger" role="alert" style={{ marginTop: '1em' }}>
              {fileError}
            </div>
          )}

          <div style={{ marginTop: '2em', display: 'flex', gap: '10px' }}>
            <button 
              className="btn btn-primary" 
              disabled={!file || status === 'uploading'}
              onClick={handleUpload}
            >
              {status === 'uploading' ? t('encrypting', lang) : t('submit_doc', lang)}
            </button>
            {requestInfo.allowMultiple && requestInfo.blobUri && (
              <button 
                type="button" 
                className="btn btn-default" 
                onClick={handleDone}
              >
                Complete Multiple Uploads
              </button>
            )}
          </div>
          </>
          )}
        </fieldset>
      )}
    </div>
  );
}

// frontend/src/UploaderView.vue
<template>
  <div>
    <h1 v-if="status === 'loading'" id="main-content">{{ t('loading') }}</h1>
    <div v-else-if="status === 'already_uploaded'" class="alert alert-success">
      <h2 style="margin-top: 0">{{ t('fulfilled') }}</h2>
      <p>{{ t('fulfilled_desc') }}</p>
    </div>
    <div v-else-if="status === 'error'" class="alert alert-danger">
      <h2 style="margin-top: 0">{{ t('invalid_link') }}</h2>
      <p>{{ t('invalid_link_desc') }}</p>
    </div>
    <div v-else-if="status === 'success'" class="alert alert-success">
      <h2 style="margin-top: 0">{{ t('success') }}</h2>
      <p>{{ t('success_desc') }}</p>
    </div>
    <div v-else>
      <h1 id="main-content">{{ t('portal_title') }}</h1>
      <p>{{ t('portal_desc') }}</p>
      
      <div v-if="requestInfo?.caseNumber" style="margin-bottom: 1em; padding: 1em; background-color: #f0f0f0; border-left: 4px solid #0066cc;">
        <strong>{{ t('case_number_label') }}</strong> {{ requestInfo.caseNumber }}
      </div>

      <fieldset v-if="status === 'ready'">
        <legend>{{ t('auth_req') }}</legend>
        <p>{{ t('auth_req_desc') }}</p>
        <div v-if="secretError" class="alert alert-danger" role="alert">{{ secretError }}</div>
        <form @submit.prevent="handleAuthenticate">
          <div class="form-group">
            <label for="secretInput">{{ t('secret') }}</label>
            <input type="password" id="secretInput" class="form-control" v-model="secret" required />
          </div>
          <div style="display: flex; gap: 10px;">
            <button type="submit" class="btn btn-primary">{{ t('access_portal') }}</button>
            <button type="button" class="btn btn-default" @click="handleSend2fa" :disabled="cooldown > 0">
              {{ cooldown > 0 ? `Wait ${cooldown}s` : 'Send Passcode' }}
            </button>
          </div>
        </form>
      </fieldset>

      <fieldset v-if="status === 'authenticated' || status === 'uploading'">
        <legend>{{ t('upload_doc') }}</legend>

        <div v-if="requestInfo?.blobUri && !requestInfo?.allowMultiple" class="alert alert-success" style="margin-bottom: 1.5em;">
          <strong>{{ t('upload_complete_single_file') }}</strong>
        </div>
        
        <div v-if="requestInfo?.blobUri && requestInfo?.allowMultiple" class="alert alert-info" style="margin-bottom: 1.5em;">
          <strong>{{ t('files_uploaded_for_request') }}</strong>
          <ul style="margin: 0.5em 0 0; padding-left: 1.5em;">
            <li v-for="(blob, idx) in requestInfo.blobUri.split(',')" :key="idx">{{ blob }}</li>
          </ul>
          <p style="margin-top: 0.5em;">{{ t('upload_more_files_allowed') }}</p>
        </div>

        <div v-if="!requestInfo?.blobUri || requestInfo?.allowMultiple">
          <p><strong>{{ t('allowed_file_types') }}</strong> {{ requestInfo?.requestedFileTypes }}</p>
          
          <div 
            class="dropzone"
            @click="fileInputRef?.click()"
            @dragover.prevent
            @drop.prevent="handleDrop"
            role="button"
            tabindex="0"
            :aria-label="t('click_drag')"
            @keydown.enter="fileInputRef?.click()"
            @keydown.space="fileInputRef?.click()"
          >
            <UploadCloud :size="48" class="dropzone-icon" aria-hidden="true" />
            <p v-if="file" class="dropzone-text">{{ t('selected') }} {{ file.name }} ({{ (file.size / 1024 / 1024).toFixed(2) }} MB)</p>
            <p v-else class="dropzone-text">{{ t('click_drag') }}</p>
            <input 
              type="file" 
              ref="fileInputRef" 
              style="display: none;" 
              @change="handleFileChange"
              :accept="allowedAcceptExts" 
              aria-hidden="true"
              tabindex="-1"
            />
          </div>
          
          <div v-if="fileError" class="alert alert-danger" role="alert" style="margin-top: 1em;">
            {{ fileError }}
          </div>

          <div style="margin-top: 2em; display: flex; gap: 10px;">
            <button class="btn btn-primary" :disabled="!file || status === 'uploading'" @click="handleUpload">
              {{ status === 'uploading' ? t('encrypting') : t('submit_doc') }}
            </button>
            <button v-if="requestInfo?.allowMultiple && requestInfo?.blobUri" type="button" class="btn btn-default" @click="handleDone">
              Complete Multiple Uploads
            </button>
          </div>
        </div>
      </fieldset>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import { useRoute } from 'vue-router';
import axios from 'axios';
import { UploadCloud } from 'lucide-vue-next';
import { useLanguage, t as tRoot } from './i18n';

const API_BASE = 'http://localhost:3001/api/public';
const route = useRoute();
const { lang } = useLanguage();

const t = (key: string) => tRoot(key);
const token = route.params.token as string;

const allowedAcceptExts = computed(() => {
  if (!requestInfo.value?.requestedFileTypes) return '*';
  return requestInfo.value.requestedFileTypes.split(',').map((ext: string) => `.${ext.trim()}`).join(',');
});

const requestInfo = ref<any>(null);
const file = ref<File | null>(null);
const status = ref('loading');
const secret = ref('');
const secretError = ref('');
const fileError = ref('');
const cooldown = ref(0);
const fileInputRef = ref<HTMLInputElement | null>(null);

let cooldownTimer: number | undefined;

watch(cooldown, (newVal) => {
  if (cooldownTimer) clearTimeout(cooldownTimer);
  if (newVal > 0) {
    cooldownTimer = setTimeout(() => cooldown.value--, 1000) as unknown as number;
  }
});

onUnmounted(() => {
  if (cooldownTimer) clearTimeout(cooldownTimer);
});

onMounted(() => {
  axios.get(`${API_BASE}/requests/${token}`)
    .then(res => {
      requestInfo.value = res.data;
      if (res.data.isClosed || (res.data.blobUri && !res.data.allowMultiple)) {
        status.value = 'already_uploaded';
      } else {
        status.value = res.data.requiresSecret ? 'ready' : 'authenticated';
      }
    })
    .catch(() => {
      status.value = 'error';
    });
});

const handleAuthenticate = async () => {
  secretError.value = '';
  try {
    await axios.post(`${API_BASE}/requests/${token}/validate-secret`, { secret: secret.value });
    if (requestInfo.value?.isClosed || (requestInfo.value?.blobUri && !requestInfo.value?.allowMultiple)) {
      status.value = 'already_uploaded';
    } else {
      status.value = 'authenticated';
    }
  } catch (err) {
    secretError.value = t('invalid_link_desc');
  }
};

const handleSend2fa = async () => {
  try {
    await axios.post(`${API_BASE}/requests/${token}/send-uploader-2fa`);
    cooldown.value = 60;
    secretError.value = '';
    alert('2FA Passcode sent to your email.');
  } catch (err: any) {
    if (err.response?.status === 429) {
      secretError.value = 'Please wait 1 minute before requesting another code.';
    } else {
      secretError.value = 'Failed to send 2FA code.';
    }
  }
};

const handleDrop = (e: DragEvent) => {
  if (e.dataTransfer?.files[0]) {
    checkAndSetFile(e.dataTransfer.files[0]);
  }
};

const handleFileChange = (e: Event) => {
  const target = e.target as HTMLInputElement;
  if (target.files && target.files[0]) {
    checkAndSetFile(target.files[0]);
  }
};

const checkAndSetFile = (selectedFile: File) => {
  const allowedExtensions = requestInfo.value?.requestedFileTypes
    ?.split(',')
    .map((ext: string) => ext.trim().toLowerCase().replace(/^[\.]/, ''))
    .filter(Boolean) || [];
  const fileExt = selectedFile.name.split('.').pop()?.toLowerCase() || '';

  if (allowedExtensions.length > 0 && fileExt && !allowedExtensions.includes(fileExt)) {
    file.value = null;
    fileError.value = `Invalid file type. Allowed: ${requestInfo.value?.requestedFileTypes}`;
    return;
  }

  file.value = selectedFile;
  fileError.value = '';
};

const handleUpload = async () => {
  if (!file.value) return;
  status.value = 'uploading';

  try {
    const sasRes = await axios.post<{ url: string, blobName: string }>(`${API_BASE}/requests/${token}/sas`, { filename: file.value.name, secret: secret.value });
    const { url, blobName } = sasRes.data;

    await axios.put(url, file.value, {
      headers: {
        'x-ms-blob-type': 'BlockBlob',
        'Content-Type': file.value.type || 'application/octet-stream'
      }
    });

    await axios.post(`${API_BASE}/requests/${token}/confirm`, { blobName });

    const res = await axios.get(`${API_BASE}/requests/${token}`);
    requestInfo.value = res.data;
    file.value = null;
    
    if (!res.data.allowMultiple) {
      status.value = 'success';
    } else {
      status.value = 'authenticated';
    }
  } catch (error) {
    console.error('Upload error', error);
    status.value = 'error';
  }
};

const handleDone = async () => {
  try {
    if (!window.confirm(t('confirm_complete_upload'))) {
      return;
    }
    await axios.post(`${API_BASE}/requests/${token}/complete`);
    status.value = 'already_uploaded';
  } catch (error) {
    console.error('Complete error', error);
    status.value = 'error';
  }
};
</script>
